name: Node.js CI/CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn add sharp --ignore-engines
      - run: |
          echo "DB_URI=${{ secrets.DATABASE_URL }}" >> .env
          echo "${{ secrets.BOT_TOKEN }}" >> .env
          echo "${{ secrets.SPOTIFY_CLIENT_ID }}" >> .env
          echo "${{ secrets.SPOTIFY_SECRET_ID }}" >> .env
          echo 'IMGUR_CLIENT_ID='${{ secrets.IMGUR_CLIENT_ID }}"' >> .env
          echo 'IMGUR_CLIENT_SECRET="${{ secrets.IMGUR_CLIENT_SECRET }}"' >> .env
      - run: pm2 restart all
